server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
          filters:
            - AddRequestHeader=Employee-Request, This is an Employee request
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**
          filters:
            - AddRequestHeader=Department-Request, This is a Department request

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Config Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
