server:
  port: 8081
spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: quannguyen2004
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

DEPARTMENT-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule